# fly.toml file generated for codewars-discord-bot on 2022-12-02T10:49:51-08:00

app = "codewars-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true
